In [1]:
import numpy as np

In [5]:
mylist = [1,2,3,4,5]
nparray = np.array(mylist)
nparray

array([1, 2, 3, 4, 5])

In [6]:
one_vector = np.ones(5)
zero_vertor = np.zeros(5)
print one_vector, zero_vertor

[ 1.  1.  1.  1.  1.] [ 0.  0.  0.  0.  0.]


In [10]:
ones_2Darray = np.ones((2,4))
print ones_2Darray

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [17]:
empty_vector = np.empty(5)
print empty_vector

[ 0.  0.  0.  0.  0.]


In [18]:
nparray[2]

3

In [25]:
my_vector = np.array([1,2,3,4,5])
print my_vector

[1 2 3 4 5]


In [30]:
my_matrix = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print my_matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print my_matrix[1,2]

6


In [33]:
print my_matrix[0:2,2]

[3 6]


In [35]:
print my_matrix[0:2,0:2]

[[1 2]
 [4 5]]


In [40]:
fib_indices = np.array([1, 1, 2, 3])
random_vector = np.random.random(10) # 10 random numbers between 0 and 1
print random_vector

[ 0.23025852  0.92409921  0.84155132  0.7324361   0.5792678   0.5617795
  0.30378769  0.79480406  0.73486427  0.61286981]


In [41]:
print random_vector[fib_indices]

[ 0.92409921  0.92409921  0.84155132  0.7324361 ]


In [42]:
my_vector = np.array([1, 2, 3, 4])
select_index = np.array([True, False, True, False])
print select_index
print my_vector[select_index]

[ True False  True False]
[1 3]


In [43]:
select_cols = np.array([True, False, True]) # 1st and 3rd column
select_rows = np.array([False, True]) # 2nd row
print select_cols, select_rows

[ True False  True] [False  True]


In [44]:
print my_matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
print my_matrix[select_rows, :]

[[4 5 6]]


In [48]:
print my_matrix[:,select_cols]

[[1 3]
 [4 6]
 [7 9]]


In [49]:
print my_matrix[select_rows,select_cols]

[4 6]


In [53]:
my_array = np.array([1, 2, 3, 4])
print my_array*my_array

[ 1  4  9 16]


In [54]:
print my_array**2

[ 1  4  9 16]


In [55]:
print my_array - np.ones(4)

[ 0.  1.  2.  3.]


In [56]:
print my_array + np.ones(4)

[ 2.  3.  4.  5.]


In [61]:
my_array = np.array([1., 2., 3., 4.])
print my_array

[ 1.  2.  3.  4.]


In [62]:
print my_array / 3

[ 0.33333333  0.66666667  1.          1.33333333]


In [63]:
print my_array / np.array([2., 3., 4., 5.])

[ 0.5         0.66666667  0.75        0.8       ]


In [64]:
print np.sum(my_array)

10.0


In [65]:
print np.average(my_array)

2.5


In [66]:
print np.sum(my_array)/len(my_array)

2.5


In [67]:
sum(my_array)

10.0

In [81]:
array1 = np.array([1., 2., 3., 4.])
array2 = np.array([2., 3., 4., 5.])


40.0


In [89]:
print np.dot(array1, array2)
print sum(array1*array2)
print np.sum(array1*array1)

40.0
40.0
30.0


In [82]:
sum(array1*array2)

40.0

In [83]:
np.sqrt(sum(array1*array2))

6.324555320336759

In [84]:
array1_mag = np.sqrt(np.dot(array1, array1))
print array1_mag

5.47722557505


In [85]:
print np.sum(array1*array1)
print np.sqrt(np.sum(array1*array1))

30.0
5.47722557505


In [90]:
my_features = np.array([[1., 2.], [3., 4.], [5., 6.], [7., 8.]])
print my_features

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [91]:
my_weights = np.array([0.4, 0.5])
print my_weights

[ 0.4  0.5]


In [97]:
print np.dot(my_features, my_weights)

[ 1.4  3.2  5.   6.8]


In [98]:
matrix_1 = np.array([[1., 2., 3.],[4., 5., 6.]])
print matrix_1

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [99]:
matrix_2 = np.array([[1., 2.], [3., 4.], [5., 6.]])
print matrix_2

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [100]:
print np.dot(matrix_1, matrix_2)

[[ 22.  28.]
 [ 49.  64.]]
